export const properties = {
  Port: "http://localhost:8080/",
  // Port: "../wms-application/",
  loginURL: "user/autheticateUser/",
  getListOfFilterDataForChangeStatus:
    "changeStatus/getListOfFilterDataForChangeStatus",
    getlistofboxreplacementbyfiltercriteria:"boxreplacement/getlistofboxreplacementbyfiltercriteria",
  getAllFamilyByFilterCriteria: "family/getAllFamilyByFilterCriteria",
  listOfAllFamilyDEScriptions: "family/listOfAllFamilyDEScriptions",
  deleteFamily: "family/deleteFamily/",
  createFamilyKLOthers: "family/createFamilyKLOthers",
  getlistofstocksnapshotfiltercriteria:
    "snapshot/getlistofstocksnapshotfiltercriteria",
    replaceContainerByContainerId:"boxreplacement/replaceContainerByContainerId/",
       boxReplaceWithAnotherBatch:"boxreplacement/replaceBoxWithAnotherBatch",
  listOfContentEntities: "snapshot/listOfContentEntities/",
  getListOfMotiveStockForContentStatus:
    "changeStatus/getListOfMotiveStockForContentStatus",
  changeContentStatus: "changeStatus/changeContentStatus",
  deleteeRackProfile: "rackprofile/deleteeRackProfile/",
  getListOfRackProfile: "rackprofile/getListOfRackProfile",
  createRackProfile: "rackprofile/createRackProfile",
  getListOfProfileLineByIdRackCell:
    "rackprofile/getListOfProfileLineByIdRackCell/",
  getListOfAllGatesKL: "TrailerRelease/getListOfAllGates",
  getListOfPreparationOrders: "preparationorder/getListOfPreparationOrders",
  GetProductListOfAllFilters: "product/getListofAllFilterData",
  getListOfAllDispatchMode: "WaveKLP/getListOfAllDispatchMode",
  createAndSelectWave: "wave/createAndSelectWave",
  createWaveSH: "WaveSH/createWaveSH",
  getProductKLLUbyIdProduct: "product/getProductKLLUbyIdProduct/",
  GetListOfSiloLoadingSiCl: "siloLoading/getListOfSiloLoadingSiCl",
  GetListOfSiloSICLView: "silo/getListOfSiloSICLView",
  GetSiloLoadingSiClBysiloNumberL3:
    "siloLoading/getSiloLoadingSiClBysiloNumberL3/",
  GetListOfPackingLineView: "repacking/getListOfPackingLineView",
  GetParameterFilterList: "parameter/GetListOfParameter",
  UpdateParameterValue: "parameter/UpdateParameterValue",
  CreateParameterValue: "parameter/CreateParameterValue",
  DeleteParameterValue: "parameter/DeleteParameterValue",
  GetListOfSites: "site/getListOfSites",
  getListOfContact: "Contact/getListOfContacts",
  createContact: "Contact/createContact",
  updateContact: "Contact/updateContact",
  deleteContact: "Contact/deleteContact",
  getListOfCompanies: "company/getListOfCompanies",
  deleteCompany: "company/deleteCompany",
  updateCompany: "company/updateCompany",
  createCompany: "company/createCompany",
  GetListOfRoles: "role/getListofAllFilteredDataForRole",
  GetListOfUsersByFilterCriteria: "user/getListOfUser",
  getListofPackagingforContainercreation:
    "Container/getListofPackagingforContainercreation/",
  // getListOfContentStatus: "ContentStatus/getListOfContentStatus",
  getProductkllubyReferenceid: "product/getProductkllubyReferenceid/",
  listofThermalprinter: "PrinterThermalExcController/getlistofprinterthermal",
  printBarCode: "barcode/printBarcode/",
  getListofPackagingforContainercreation:
    "Container/getListofPackagingforContainercreation/",
  getListOfContentStatus: "ContentStatus/getListofDescriptionFromContentStatus",
  getListOfDescriptionFromContentStatus:
    "ContentStatus/getListofDescriptionFromContentStatus",
  getProductkllubyReferenceid: "product/getProductkllubyReferenceid/",
  getProductByIdReference: "product/getProductByIdReference/",
  Containercreatecode: "NB_MAX_CONTAINER_CREATE;",
  GetParameterValue: "parameter/GetParameterValue/",
  getlistofallprinterthermal:
    "PrinterThermalExcController/getlistofallprinterthermal",
  addContainerKL: "Container/addContainerKL",
  checkProcessOrderProduct: "Container/checkProcessOrderProduct/",
  getListOfGateKl: "ShippingGate/getListOfPhysicalGates",
  createGateKl: "ShippingGate/createGateKl",
  deleteGateKl: "ShippingGate/deleteGateKl",
  printLabel: "printing/printPalletLabel/",
  getListofStockByBatch: "stockbybatch/getListofStockByBatch",
  getRegions: "stockbybatch/getRegions",
  getWarehouses: "stockbybatch/getWarehouses",
  getListofStockByLocation: "stockbylocation/getListofStockByLocation",
  getLocationRegions: "stockbylocation/getRegions",
  getLocationWarehouses: "stockbylocation/getWarehouses",
  getLocationRegions: "stockbylocation/getRegions",
  getLocationWarehouses: "stockbylocation/getWarehouses",
  getDescriptionListForPhysicalGate:
    "ShippingGate/getDescriptionListForPhysicalGate",
  getTypeAssignmentsForPhysicalgate: "ShippingGate/getTypeAssignments",
  getTypeAssignmentforinterstock:"ShippingGate/getTypeAssignmentforinterstock",
  getTypeAssignmentforgoodsin:"ShippingGate/getTypeAssignmentforgoodsin",
  getTypeAssignmentforshipping:"ShippingGate/getTypeAssignmentforshipping",
  getWarehousesForPhysicalgate: "/ShippingGate/getWarehouses",
  getListOfAllCarrier: "WaveKLP/getListOfAllCarrier",
  getListOfLogicalGates: "ShippingGate/getListOfLogicalGates",
  getDescriptionListForLogicalGate:
    "ShippingGate/getDescriptionListForLogicalGate",
  getListOfCellDescription: "CellModels/getListOfDescription",
  getListOfCellModels: "CellModels/getListOfCellModels",
  deleteCellModel: "CellModels/deleteCellModel",
  createCellModel: "CellModels/createCellModel",
  getListOfMissionClass: "OperationByRegion/getListOfMissionClass",
  getListOfOperationByRegion: "OperationByRegion/getListOfOperationByRegion",
  getlistofRegionsWHEntities: "location/getlistofRegionsWHEntities",
  createRegionMissionDistribution:
    "OperationByRegion/createRegionMissionDistribution",
  updateRegionMissionDistribution:
    "OperationByRegion/updateRegionMissionDistribution",
  deleteRegionMissionDistribution:
    "OperationByRegion/deleteRegionMissionDistribution",
  getStockByLocationByBatch: "stockbylocation/getStockByLocationByBatch/",
  deleteRegionKLS: "location/deleteRegionKLS/",
  getListOfRepackingLineView: "repacking/getListOfRepackingLineView",
  // ----------------------------->>>>>>>>>>>>>>>>>>>>

  getListofPalletMovement: "location/getListofPalletMovement",
  getlistofRegionsRTEntities: "location/getlistofRegionsRTEntities",
  getlistofRegionsWHEntities: "location/getlistofRegionsWHEntities",
  getListOfAllWarehouse: "warehouse/getListOfAllWarehouse",
  getRegiondatabyregionid: "location/getRegiondatabyregionid/",

  getKLContainer: "Container/getKLContainerbyFilterCriteria",
  getListOfPackagingKL: "packaging/getListOfPackagingKL",
  palletMovementConfirmValidation: "palletMovementController/confirmValidation",
  getlogin: "user/Login",
  SingleCancellation: "Mission/SingleCancellation",
  getListOfMissionKLS: "Mission/getListOfClassMissionKls",
  geteditClassMissionkls:"Mission/editClassMissionKls",
  getClassMissionKlsById:"Mission/getClassMissionKlsById",
  validateMission: "Mission/validateMission",
  getMissionViewById: "Mission/getMissionViewById/",
  getListOfResource: "role/getListOfResource",
  getRoleById: "role/getRoleById",
  getlistOfResourcesAvailable: "role/getlistOfResourcesAvailable",
  createRole: "role/createRole",
  createRoleAcess: "role/createRoleAcess",
  fileIntegrate: "fileIntegration/integrate",
  deleteroleByRoleId: "role/deleteroleByRoleId/",
  getSiteParameterBySiteId: "SiteParameter/getSiteParameterBySiteId/",
  createSite: "site/createSite",
  deleteSite: "site/deleteSite/",
  updateWarehouse: "warehouse/updateWarehouse",
  deleteWarehouseNew: "warehouse/deleteWarehouseNew/",
  editWarehouse: "warehouse/editWarehouse",
  CreateUpdateWarehouse: "warehouse/CreateUpdateWarehouse",
  updateContentStatus: "ContentStatus/updateContentStatus",
  createContentStatus: "ContentStatus/createContentStatus",
  getListOfContentStatusss: "ContentStatus/getListOfContentStatus",
  deleteContentStatus: "ContentStatus/deleteContentStatus",
  createPackagingKL: "packaging/createPackagingKL",
  getListOfPackagingKLPView: "packaging/getListOfPackagingKLPView",
  deletePackaging: "packaging/deletePackaging/",
  updateProductKLLUbyLUid: "product/updateProductKLLUbyLUid",
  getListofAllFilteredDataForLUproduct:
    "product/getListofAllFilteredDataForLUproduct",
  editProduct: "product/editProduct",
  deleteProductByIdWithIMC: "product/deleteProductByIdWithIMC/",
  getListOfCellAccessByFilterCriteria:
    "location/getListOfCellAccessByFilterCriteria",
  getListOfAllRegionsWarehouseDescription:
    "location/getListOfAllRegionsWarehouseDescription",
  getListOfDescription: "CellModels/getListOfDescription",
  getListOfProfileFamily: "location/getListOfProfileFamily",
  updateRegionCellAccessibilityByIds:
    "location/updateRegionCellAccessibilityByIds",
  getListOfRegionByFilterCriteria: "location/getListOfRegionByFilterCriteria",
  getListOfWarehouseById: "warehouse/getListOfWarehouseById/",
  getlistOfAllAlphabets: "location/getlistOfAllAlphabets",
  getListOfPreparationBoxesViewBeansByFilterCriteria:
    "preparationorder/getListOfPreparationBoxesViewBeansByFilterCriteria",
  getCompanyById: "company/getCompanyById/",
  listofTrailerExitViewbyFilter:
    "ShippingTrailer/listofTrailerExitViewbyFilter",
  getListOfAssociatedTrailers: "Trailer/getListOfAssociatedTrailers",
  getViewUncubedPoLineId: "preparationorder/getViewUncubedPoLineId/",
  getListOfUncubedPOLineFilterCriteriaa:
    "preparationorder/getListOfUncubedPOLineFilterCriteriaa",
  createAndSelectWave: "wave/createAndSelectWave",
  getListOfWave: "WaveSH/getListOfWave",
  getListOfWaveklp: "WaveKLP/getListOfWave",
  getListOfRepackingLineByPackingLine:
    "repacking/getListOfRepackingLineByPackingLine/",
  closeRejectedRepackingLine: "repacking/closeRejectedRepackingLine/",
  sendRepackingToDCS: "repacking/sendRepackingToDCS/",
  editRePackingLineSICL: "repacking/editRePackingLineSICL",
  getlistofContentbyFilterCriteria: "Content/getlistofContentbyFilterCriteria",
  getKLContainerbyFilterCriteria: "Container/getKLContainerbyFilterCriteria",
  getListOfMasterMissionByFilterCriteria:
    "MasterMission/getListOfMasterMissionByFilterCriteria",
  updateMasterMission: "MasterMission/updateMasterMission",
  getListOfDescriptionEntities: "MasterMission/getListOfDescriptionEntities",
  MultiCancellation: "Mission/MultiCancellation",
  createUser: "user/createUser",
  getSiteById: "site/getSiteById/",
  getlistOfAllCompanies: "company/getlistOfAllCompanies",
  getlistOfAllSites: "site/getlistOfAllSites",
  listOfRolesWithAccessAndResources: "role/listOfRolesWithAccessAndResources",
  getListOfLanguage: "language/getListOfLanguage",
  getdefaultWarehouse: "warehouse/getdefaultWarehouse",
  getUserById: "user/getUserById/",
  getListOfAllUserData: "user/getListOfAllUserData",
  deleteUserByUserId: "user/deleteUserByUserId/",
  getDetailsForWaveLaunch: "wave/getDetailsForWaveLaunch/",
  getSalesTermforWaveLaunch: "wave/getSalesTermforWaveLaunch",
  getListOfGatesForWaveLaunch: "wave/getListOfGatesForWaveLaunch",
  getlistofcontentonlystatus: "Content/getListOfContentStatus",
  getPreparationOrderbyWaveId: "preparationorder/getPreparationOrderbyWaveId/",
  getListOfTrailerReleaseViewFilter:
    "TrailerRelease/listofTrailerfilterrrrrrrrr",
  getListOfPackagingKL: "packaging/getListOfPackagingKL",
  lauchWave: "wave/lauchWave",
  AddLineServiceMethod: "WaveKLP/AddLineServiceMethod",
  getGateDetailsByGateNo: "ShippingGate/getGateDetailsByGateNo/",
  ShippingGate: "ShippingGate/save",
  deleteWave: "WaveKLP/deleteWave/",
  RemoveAddedPOLine: "/WaveKLP/removeAddedPOLinefromWave",
  getListOfWaveDetailsByWaveId: "WaveSH/getListOfWaveDetailsByWaveId/",
  getListOfTrailer: "Trailer/getListOfTrailer",
  cancelMission: "Mission/cancelMission",
  triggerCronicJobs: "triggerCronicJobs",
  getAssociatedTrailerbyPrepId: "Trailer/getAssociatedTrailerbyPrepId/",
  updateTrailer: "Trailer/updateTrailer",
  disassociateTrailer: "Trailer/disassociateTrailer",
  releaseTrailer: "TrailerRelease/releaseTrailer/",
  TrailerExit: "ShippingTrailer/trailerExit/",
  cancelPreparationByIdpo: "preparationorder/cancelPreparationByIdpo/",
  getListOfAllPackaging: "rackprofile/getListOfAllPackaging/",
  getDescListOfRackProfile: "rackprofile/getDescListOfRackProfile/",
  createProfileLine: "rackprofile/createProfileLine",
  //createRackProfile:"/rackprofile/createRackProfile",
  deletekProfileLine: "/rackprofile/deletekProfileLine/",
  getDescOfParameter: "parameter/getDescOfParameter",
  getWaveShbyIdWave: "WaveSH/getWaveShbyIdWave/",
  getWaveDetailsbyIdWave: "wave/getWaveDetailsForIdWave/",
  getHistorybyIdpo: "preparationorder/getHistorybyIdpo/",
  generateLoadingVoucher : "pdf/generateLoadingVoucher/",
  listofLaserprinter : "PrinterLaserExcController/GetListofPrinterLaserExc",
  getPackingLineByMaterialType: "repacking/getPackingLineByMaterialType/",
  getListOfSiloByMaterialType: "silo/getListOfSiloByMaterialType/",
  editRePackingLineSICL: "repacking/editRePackingLineSICL",
  getListofDestructionContainers: "palletDestruction/getListofDestructionContainer",
  getRegionForPalletDestruction: "palletDestruction/getRegionForPalletDestruction",
  getRegionDescForPalletDestruction: "palletDestruction/getRegionDescForPalletDestruction",
  getListOfMotiveStockForPalletDestruction: "palletDestruction/getListOfMotiveStockForPalletDestruction",
  palletDestructionConfirmValidation: "palletDestruction/confirmDestruction"
};
